// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"goflare.io/auth/authentication"
	"goflare.io/auth/authorization"
	"goflare.io/auth/config"
	"goflare.io/auth/firebase"
	"goflare.io/auth/handler"
	"goflare.io/auth/middleware"
	"goflare.io/auth/role"
	"goflare.io/auth/server"
	"goflare.io/auth/user"
)

// Injectors from wire.go:

func InitializeAuthService() (*server.Server, error) {
	configConfig, err := config.ProvideApplicationConfig()
	if err != nil {
		return nil, err
	}
	postgresPool, err := config.ProvidePostgresConn(configConfig)
	if err != nil {
		return nil, err
	}
	logger := config.NewLogger()
	repository := user.NewRepository(postgresPool, logger)
	enforcer, err := config.ProvideEnforcer(configConfig, logger)
	if err != nil {
		return nil, err
	}
	service := authentication.NewService(repository, configConfig, enforcer, logger)
	authenticationMiddleware := middleware.NewAuthenticationMiddleware(service)
	client, err := firebase.NewFirebaseClient()
	if err != nil {
		return nil, err
	}
	firebaseService := firebase.NewService(repository, client, logger)
	userHandler := handler.NewUserHandler(service, firebaseService)
	roleRepository := role.NewRepository(postgresPool, logger)
	authorizationService := authorization.NewService(repository, roleRepository, enforcer, logger)
	serverServer := server.NewServer(authenticationMiddleware, userHandler, service, authorizationService, logger)
	return serverServer, nil
}
