// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go.flare.io/auth"
	"go.flare.io/auth/config"
	"go.flare.io/auth/permission"
	"go.flare.io/auth/role"
	"go.flare.io/auth/user"
)

// Injectors from wire.go:

func InitializeAuthService() (auth.Authentication, error) {
	appConfig := config.ProvideApplicationConfig()
	postgresPool := config.ProvidePostgresConn(appConfig)
	logger := config.NewLogger()
	repository := user.NewRepository(postgresPool, logger)
	service := user.NewService(repository)
	roleRepository := role.NewRepository(postgresPool, logger)
	roleService := role.NewService(roleRepository)
	permissionRepository := permission.NewRepository(postgresPool, logger)
	permissionService := permission.NewService(permissionRepository)
	pasetoSecret := config.ProvidePasetoSecret(appConfig)
	enforcer, err := config.ProvideEnforcer(appConfig)
	if err != nil {
		return nil, err
	}
	authentication := auth.NewAuthentication(service, roleService, permissionService, pasetoSecret, enforcer)
	return authentication, nil
}
